set(0,'DefaultAxesFontName', 'DejaVu Sans',...
'DefaultLineLineWidth', 1,...
'DefaultAxesXGrid', 'on',...
'DefaultAxesYGrid', 'on',...
'DefaultTextFontName', 'DejaVu Sans',...
'DefaultTextFontSize', 14,...
'DefaultFigurePosition', [-1850, 400, 950, 580],...
'DefaultAxesFontSize', 12)
